# Generated by Django 5.0 on 2024-01-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_phone',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
